apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-demo
  template:
    metadata:
      labels:
        app: insecure-demo
    spec:
      hostNetwork: true
      containers:
        - name: app
          image: example.invalid/demo:latest
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 0
          ports:
            - containerPort: 8080
